### ISSUE TITLE
504 Gateway Timeout with provided credentials

### ISSUE THREAD

**Issue by andyvanee** [octohost/mysql-plugin#1]
Related to octohost/octohost-cookbook#12 I'm having problems connecting to the DB with the supplied credentials. Is there something more that needs to happen to expose the port. This is my test connection script:

https://gist.github.com/andyvanee/fe5374a0e3d60bd40853

**Comment by darron** [comment]
The plugin really just sets up usernames, passwords and databases - and I can connect to the right database using the supplied username and password.

There's something else going on.
